### ISSUE TITLE
Add a plus button at the bottom, top or both to create a new tab

### ISSUE THREAD

**Issue by zeroarst** [Able-Bear-Software/tab-nodes-tree#35]
### Discussed in https://github.com/Able-Bear-Software/tab-nodes-tree/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **zeroarst** September 20, 2024</sup>
A quick-add button at the bottom for users to easily create a new tab could be helpful. Adding settings like holding Shift while clicking to open it as a child tab might be useful too.</div>

**Comment by zeroarst** [comment]
![image](https://github.com/user-attachments/assets/1f784b04-0683-4d3f-bf93-ee93e17ad3ee)

**Comment by Tab-Nodes-Tree** [comment]
Final revision:
![image](https://github.com/user-attachments/assets/17be31d3-00a0-464f-b785-4dd786c86454)
