### ISSUE TITLE
Add a keyboard shortcut to show/hide Tab Nodes Tree

### ISSUE THREAD

**Issue by zeroarst** [Able-Bear-Software/tab-nodes-tree#37]
### Discussed in https://github.com/Able-Bear-Software/tab-nodes-tree/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **zeroarst** October  1, 2024</sup>
A reddit user asked if there is a keyboard  shortcut to open/close Tab Nodes Tree.
https://www.reddit.com/r/chrome_extensions/comments/10jls57/comment/lps67sk/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button</div>

**Comment by stefan123t** [comment]
This is to show / hide the Tab Nodes Tree sidebar. Just trying to distinguish the goals of various issues dealing with "closing".

**Comment by zeroarst** [comment]
@stefan123t I think I can close this ticket since there is already a built-in shortcut for it.
![image](https://github.com/user-attachments/assets/1894e236-9d6e-4163-971e-50afcb85712b)

**Comment by stefan123t** [comment]
@zeroarst thanks for adding this in dev. 
I noticed that the sidebar is not automatically opened when I start Chrome, e.g. after a reboot.
I have to enable the extension from the plugin toolbar to show the tabs on the sidebar.
Is that initial setting also configurable / changed with the above hotkey assignment ?

**Comment by zeroarst** [comment]
@stefan123t Chrome does not allow developers to do that. It requies user action such as clicking action icon, keyboard shortcut..etc.
https://developer.chrome.com/docs/extensions/reference/api/sidePanel#open-action-icon
https://github.com/GoogleChrome/chrome-extensions-samples/issues/982
