### ISSUE TITLE
Allow expand/collapse a group by clicking on the group tab node.

### ISSUE THREAD

**Issue by zeroarst** [Able-Bear-Software/tab-nodes-tree#62]
A new setting could be added for the user to choose whether they want to do that by single click (tab needs to be active first), or double click.

### Discussed in https://github.com/Able-Bear-Software/tab-nodes-tree/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **cschanck** October 23, 2024</sup>
The '>' is a small target, I would really like it if I could bang the header and collapse/open the entire group. </div>

**Comment by stefan123t** [comment]
I agree that this could be a good shortcut to expand / collapse a whole tree with all its subtree's.
Please consider expand / collapse as the events to distinguish them from actually closing a tab.

**Comment by zeroarst** [comment]
Uploading 2024-11-17_13-51-12.mp4…

I was considering adding a setting to enable or disable single-click functionality for expanding or collapsing. However, I'm unsure if it's truly necessary at this point. Perhaps it can be revisited in the future if users request this feature.

**Comment by zeroarst** [comment]
https://github.com/user-attachments/assets/ad0644a6-c0b9-4911-b3cb-471c677141de
I was considering adding a setting to enable or disable single-click functionality for expanding or collapsing. However, I'm unsure if it's truly necessary at this point. Perhaps it can be revisited in the future if users request this feature.

**Comment by zeroarst** [comment]
https://github.com/user-attachments/assets/4a6e0308-79aa-4fd6-9875-dd3472a797fd

**Comment by stefan123t** [comment]
I just checked the behaviour in TST and if you single click a parent tab which is collapsed it will be expanded.
If you navigate away from this tab, i.e. another collapsed parent tab, it will automagically collapse the old parent tab again and expand the current tab.

You could make it configurable to which depth the collapse / expand should automatically take place. 0 all levels depth, 1 level depth, 2 level depth, etc.

**Comment by zeroarst** [comment]
@stefan123t Thank you for your comment.
I think you are referring to another feature that always one expande subtree is visible.

This ticket will only address clicking to expand/collapse.

**Comment by zeroarst** [comment]
Uploading 2024-11-18_12-07-13.mp4…

**Comment by zeroarst** [comment]
https://github.com/user-attachments/assets/abd07a8b-fd47-44d2-a647-d372090d7228
